### PR TITLE
adding ieee and mca results

### PR DESCRIPTION
**Pull request by InesGP**

### CODE REVIEW

**Comment by glatard** [comment]
Hi Ines, not sure if we should commit the .nii.gz data, it's quite big and will bloat the repo. But happy to hear different opinions on this.

**Comment by InesGP** [comment]
ok no worries I removed the nii.gz data

**Comment by glatard** [comment]
then you should rebase otherwise the commits and their data will remain in the history.

**Comment by InesGP** [comment]
it's done!

**Pull request merged**
